YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "CAPI",
        "CAPIError",
        "ConnectionFeatureFactory",
        "ConnectionManager",
        "ContentCreateStruct",
        "ContentMetadataUpdateStruct",
        "ContentService",
        "ContentTypeCreateStruct",
        "ContentTypeGroupInputStruct",
        "ContentTypeService",
        "ContentTypeUpdateStruct",
        "ContentUpdateStruct",
        "DiscoveryService",
        "FieldDefinitionCreateStruct",
        "FieldDefinitionUpdateStruct",
        "HttpBasicAuthAgent",
        "InMemoryStorage",
        "LocalStorage",
        "LocationCreateStruct",
        "LocationUpdateStruct",
        "MicrosoftXmlHttpRequestConnection",
        "ObjectStateCreateStruct",
        "ObjectStateGroupCreateStruct",
        "ObjectStateGroupUpdateStruct",
        "ObjectStateUpdateStruct",
        "PolicyCreateStruct",
        "PolicyUpdateStruct",
        "PromiseCAPI",
        "PromiseService",
        "RelationCreateStruct",
        "Request",
        "Response",
        "RoleAssignInputStruct",
        "RoleInputStruct",
        "SectionInputStruct",
        "SessionAuthAgent",
        "SessionCreateStruct",
        "UrlAliasCreateStruct",
        "UrlWildcardCreateStruct",
        "UserCreateStruct",
        "UserGroupCreateStruct",
        "UserGroupUpdateStruct",
        "UserService",
        "UserUpdateStruct",
        "ViewCreateStruct",
        "XmlHttpRequestConnection",
        "extend",
        "parseUriTemplate"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});